// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lesson/proto/lesson.proto

package educonn_lesson

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_VIDEO Type = 0
	Type_TEXT  Type = 1
)

var Type_name = map[int32]string{
	0: "VIDEO",
	1: "TEXT",
}
var Type_value = map[string]int32{
	"VIDEO": 0,
	"TEXT":  1,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{0}
}

// ----------------------------
// LESSON
// ----------------------------
type Lesson struct {
	Base                 *LessonBase       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Stats                *LessonStatistics `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Video                *VideoLesson      `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Lesson) Reset()         { *m = Lesson{} }
func (m *Lesson) String() string { return proto.CompactTextString(m) }
func (*Lesson) ProtoMessage()    {}
func (*Lesson) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{0}
}
func (m *Lesson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lesson.Unmarshal(m, b)
}
func (m *Lesson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lesson.Marshal(b, m, deterministic)
}
func (dst *Lesson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lesson.Merge(dst, src)
}
func (m *Lesson) XXX_Size() int {
	return xxx_messageInfo_Lesson.Size(m)
}
func (m *Lesson) XXX_DiscardUnknown() {
	xxx_messageInfo_Lesson.DiscardUnknown(m)
}

var xxx_messageInfo_Lesson proto.InternalMessageInfo

func (m *Lesson) GetBase() *LessonBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *Lesson) GetStats() *LessonStatistics {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Lesson) GetVideo() *VideoLesson {
	if m != nil {
		return m.Video
	}
	return nil
}

type LessonBase struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 Type     `protobuf:"varint,4,opt,name=type,proto3,enum=educonn.lesson.Type" json:"type,omitempty"`
	UserId               string   `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LessonBase) Reset()         { *m = LessonBase{} }
func (m *LessonBase) String() string { return proto.CompactTextString(m) }
func (*LessonBase) ProtoMessage()    {}
func (*LessonBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{1}
}
func (m *LessonBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LessonBase.Unmarshal(m, b)
}
func (m *LessonBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LessonBase.Marshal(b, m, deterministic)
}
func (dst *LessonBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LessonBase.Merge(dst, src)
}
func (m *LessonBase) XXX_Size() int {
	return xxx_messageInfo_LessonBase.Size(m)
}
func (m *LessonBase) XXX_DiscardUnknown() {
	xxx_messageInfo_LessonBase.DiscardUnknown(m)
}

var xxx_messageInfo_LessonBase proto.InternalMessageInfo

func (m *LessonBase) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LessonBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LessonBase) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *LessonBase) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_VIDEO
}

func (m *LessonBase) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LessonStatistics struct {
	Likes                int64    `protobuf:"varint,1,opt,name=likes,proto3" json:"likes,omitempty"`
	Dislikes             int64    `protobuf:"varint,2,opt,name=dislikes,proto3" json:"dislikes,omitempty"`
	Views                int64    `protobuf:"varint,3,opt,name=views,proto3" json:"views,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LessonStatistics) Reset()         { *m = LessonStatistics{} }
func (m *LessonStatistics) String() string { return proto.CompactTextString(m) }
func (*LessonStatistics) ProtoMessage()    {}
func (*LessonStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{2}
}
func (m *LessonStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LessonStatistics.Unmarshal(m, b)
}
func (m *LessonStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LessonStatistics.Marshal(b, m, deterministic)
}
func (dst *LessonStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LessonStatistics.Merge(dst, src)
}
func (m *LessonStatistics) XXX_Size() int {
	return xxx_messageInfo_LessonStatistics.Size(m)
}
func (m *LessonStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_LessonStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_LessonStatistics proto.InternalMessageInfo

func (m *LessonStatistics) GetLikes() int64 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *LessonStatistics) GetDislikes() int64 {
	if m != nil {
		return m.Dislikes
	}
	return 0
}

func (m *LessonStatistics) GetViews() int64 {
	if m != nil {
		return m.Views
	}
	return 0
}

// Requests & Responses
type CreateLesson struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLesson) Reset()         { *m = CreateLesson{} }
func (m *CreateLesson) String() string { return proto.CompactTextString(m) }
func (*CreateLesson) ProtoMessage()    {}
func (*CreateLesson) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{3}
}
func (m *CreateLesson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLesson.Unmarshal(m, b)
}
func (m *CreateLesson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLesson.Marshal(b, m, deterministic)
}
func (dst *CreateLesson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLesson.Merge(dst, src)
}
func (m *CreateLesson) XXX_Size() int {
	return xxx_messageInfo_CreateLesson.Size(m)
}
func (m *CreateLesson) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLesson.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLesson proto.InternalMessageInfo

type CreateLesson_Request struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string       `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Video                *VideoLesson `protobuf:"bytes,5,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateLesson_Request) Reset()         { *m = CreateLesson_Request{} }
func (m *CreateLesson_Request) String() string { return proto.CompactTextString(m) }
func (*CreateLesson_Request) ProtoMessage()    {}
func (*CreateLesson_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{3, 0}
}
func (m *CreateLesson_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLesson_Request.Unmarshal(m, b)
}
func (m *CreateLesson_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLesson_Request.Marshal(b, m, deterministic)
}
func (dst *CreateLesson_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLesson_Request.Merge(dst, src)
}
func (m *CreateLesson_Request) XXX_Size() int {
	return xxx_messageInfo_CreateLesson_Request.Size(m)
}
func (m *CreateLesson_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLesson_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLesson_Request proto.InternalMessageInfo

func (m *CreateLesson_Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateLesson_Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateLesson_Request) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateLesson_Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateLesson_Request) GetVideo() *VideoLesson {
	if m != nil {
		return m.Video
	}
	return nil
}

type CreateLesson_Response struct {
	Lesson               *Lesson  `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLesson_Response) Reset()         { *m = CreateLesson_Response{} }
func (m *CreateLesson_Response) String() string { return proto.CompactTextString(m) }
func (*CreateLesson_Response) ProtoMessage()    {}
func (*CreateLesson_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{3, 1}
}
func (m *CreateLesson_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLesson_Response.Unmarshal(m, b)
}
func (m *CreateLesson_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLesson_Response.Marshal(b, m, deterministic)
}
func (dst *CreateLesson_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLesson_Response.Merge(dst, src)
}
func (m *CreateLesson_Response) XXX_Size() int {
	return xxx_messageInfo_CreateLesson_Response.Size(m)
}
func (m *CreateLesson_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLesson_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLesson_Response proto.InternalMessageInfo

func (m *CreateLesson_Response) GetLesson() *Lesson {
	if m != nil {
		return m.Lesson
	}
	return nil
}

type GetLesson struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLesson) Reset()         { *m = GetLesson{} }
func (m *GetLesson) String() string { return proto.CompactTextString(m) }
func (*GetLesson) ProtoMessage()    {}
func (*GetLesson) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{4}
}
func (m *GetLesson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLesson.Unmarshal(m, b)
}
func (m *GetLesson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLesson.Marshal(b, m, deterministic)
}
func (dst *GetLesson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLesson.Merge(dst, src)
}
func (m *GetLesson) XXX_Size() int {
	return xxx_messageInfo_GetLesson.Size(m)
}
func (m *GetLesson) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLesson.DiscardUnknown(m)
}

var xxx_messageInfo_GetLesson proto.InternalMessageInfo

type GetLesson_ById struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLesson_ById) Reset()         { *m = GetLesson_ById{} }
func (m *GetLesson_ById) String() string { return proto.CompactTextString(m) }
func (*GetLesson_ById) ProtoMessage()    {}
func (*GetLesson_ById) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{4, 0}
}
func (m *GetLesson_ById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLesson_ById.Unmarshal(m, b)
}
func (m *GetLesson_ById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLesson_ById.Marshal(b, m, deterministic)
}
func (dst *GetLesson_ById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLesson_ById.Merge(dst, src)
}
func (m *GetLesson_ById) XXX_Size() int {
	return xxx_messageInfo_GetLesson_ById.Size(m)
}
func (m *GetLesson_ById) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLesson_ById.DiscardUnknown(m)
}

var xxx_messageInfo_GetLesson_ById proto.InternalMessageInfo

type GetLesson_ById_Request struct {
	LessonId             string   `protobuf:"bytes,1,opt,name=lessonId,proto3" json:"lessonId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLesson_ById_Request) Reset()         { *m = GetLesson_ById_Request{} }
func (m *GetLesson_ById_Request) String() string { return proto.CompactTextString(m) }
func (*GetLesson_ById_Request) ProtoMessage()    {}
func (*GetLesson_ById_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{4, 0, 0}
}
func (m *GetLesson_ById_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLesson_ById_Request.Unmarshal(m, b)
}
func (m *GetLesson_ById_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLesson_ById_Request.Marshal(b, m, deterministic)
}
func (dst *GetLesson_ById_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLesson_ById_Request.Merge(dst, src)
}
func (m *GetLesson_ById_Request) XXX_Size() int {
	return xxx_messageInfo_GetLesson_ById_Request.Size(m)
}
func (m *GetLesson_ById_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLesson_ById_Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetLesson_ById_Request proto.InternalMessageInfo

func (m *GetLesson_ById_Request) GetLessonId() string {
	if m != nil {
		return m.LessonId
	}
	return ""
}

type GetLesson_ById_Response struct {
	Lesson               *Lesson  `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLesson_ById_Response) Reset()         { *m = GetLesson_ById_Response{} }
func (m *GetLesson_ById_Response) String() string { return proto.CompactTextString(m) }
func (*GetLesson_ById_Response) ProtoMessage()    {}
func (*GetLesson_ById_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{4, 0, 1}
}
func (m *GetLesson_ById_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLesson_ById_Response.Unmarshal(m, b)
}
func (m *GetLesson_ById_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLesson_ById_Response.Marshal(b, m, deterministic)
}
func (dst *GetLesson_ById_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLesson_ById_Response.Merge(dst, src)
}
func (m *GetLesson_ById_Response) XXX_Size() int {
	return xxx_messageInfo_GetLesson_ById_Response.Size(m)
}
func (m *GetLesson_ById_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLesson_ById_Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetLesson_ById_Response proto.InternalMessageInfo

func (m *GetLesson_ById_Response) GetLesson() *Lesson {
	if m != nil {
		return m.Lesson
	}
	return nil
}

// EVENTS
type LessonCreatedEvent struct {
	Lesson               *Lesson  `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LessonCreatedEvent) Reset()         { *m = LessonCreatedEvent{} }
func (m *LessonCreatedEvent) String() string { return proto.CompactTextString(m) }
func (*LessonCreatedEvent) ProtoMessage()    {}
func (*LessonCreatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{5}
}
func (m *LessonCreatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LessonCreatedEvent.Unmarshal(m, b)
}
func (m *LessonCreatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LessonCreatedEvent.Marshal(b, m, deterministic)
}
func (dst *LessonCreatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LessonCreatedEvent.Merge(dst, src)
}
func (m *LessonCreatedEvent) XXX_Size() int {
	return xxx_messageInfo_LessonCreatedEvent.Size(m)
}
func (m *LessonCreatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LessonCreatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LessonCreatedEvent proto.InternalMessageInfo

func (m *LessonCreatedEvent) GetLesson() *Lesson {
	if m != nil {
		return m.Lesson
	}
	return nil
}

// ----------------------------
// VIDEO-LESSON (Type: 0)
// ----------------------------
type VideoLesson struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoId              string   `protobuf:"bytes,2,opt,name=videoId,proto3" json:"videoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoLesson) Reset()         { *m = VideoLesson{} }
func (m *VideoLesson) String() string { return proto.CompactTextString(m) }
func (*VideoLesson) ProtoMessage()    {}
func (*VideoLesson) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{6}
}
func (m *VideoLesson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoLesson.Unmarshal(m, b)
}
func (m *VideoLesson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoLesson.Marshal(b, m, deterministic)
}
func (dst *VideoLesson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoLesson.Merge(dst, src)
}
func (m *VideoLesson) XXX_Size() int {
	return xxx_messageInfo_VideoLesson.Size(m)
}
func (m *VideoLesson) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoLesson.DiscardUnknown(m)
}

var xxx_messageInfo_VideoLesson proto.InternalMessageInfo

func (m *VideoLesson) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VideoLesson) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

// Requests & Responses
type CreateVideoLessonRequest struct {
	Lesson               *VideoLesson `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateVideoLessonRequest) Reset()         { *m = CreateVideoLessonRequest{} }
func (m *CreateVideoLessonRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVideoLessonRequest) ProtoMessage()    {}
func (*CreateVideoLessonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{7}
}
func (m *CreateVideoLessonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVideoLessonRequest.Unmarshal(m, b)
}
func (m *CreateVideoLessonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVideoLessonRequest.Marshal(b, m, deterministic)
}
func (dst *CreateVideoLessonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVideoLessonRequest.Merge(dst, src)
}
func (m *CreateVideoLessonRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVideoLessonRequest.Size(m)
}
func (m *CreateVideoLessonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVideoLessonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVideoLessonRequest proto.InternalMessageInfo

func (m *CreateVideoLessonRequest) GetLesson() *VideoLesson {
	if m != nil {
		return m.Lesson
	}
	return nil
}

type CreateVideoLessonResponse struct {
	Lesson               *VideoLesson `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateVideoLessonResponse) Reset()         { *m = CreateVideoLessonResponse{} }
func (m *CreateVideoLessonResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVideoLessonResponse) ProtoMessage()    {}
func (*CreateVideoLessonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{8}
}
func (m *CreateVideoLessonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVideoLessonResponse.Unmarshal(m, b)
}
func (m *CreateVideoLessonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVideoLessonResponse.Marshal(b, m, deterministic)
}
func (dst *CreateVideoLessonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVideoLessonResponse.Merge(dst, src)
}
func (m *CreateVideoLessonResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVideoLessonResponse.Size(m)
}
func (m *CreateVideoLessonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVideoLessonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVideoLessonResponse proto.InternalMessageInfo

func (m *CreateVideoLessonResponse) GetLesson() *VideoLesson {
	if m != nil {
		return m.Lesson
	}
	return nil
}

type GetVideoLessonByIdRequest struct {
	LessonId             string   `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoLessonByIdRequest) Reset()         { *m = GetVideoLessonByIdRequest{} }
func (m *GetVideoLessonByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetVideoLessonByIdRequest) ProtoMessage()    {}
func (*GetVideoLessonByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{9}
}
func (m *GetVideoLessonByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoLessonByIdRequest.Unmarshal(m, b)
}
func (m *GetVideoLessonByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoLessonByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetVideoLessonByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoLessonByIdRequest.Merge(dst, src)
}
func (m *GetVideoLessonByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetVideoLessonByIdRequest.Size(m)
}
func (m *GetVideoLessonByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoLessonByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoLessonByIdRequest proto.InternalMessageInfo

func (m *GetVideoLessonByIdRequest) GetLessonId() string {
	if m != nil {
		return m.LessonId
	}
	return ""
}

type GetVideoLessonByIdResponse struct {
	Lesson               *VideoLesson `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetVideoLessonByIdResponse) Reset()         { *m = GetVideoLessonByIdResponse{} }
func (m *GetVideoLessonByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetVideoLessonByIdResponse) ProtoMessage()    {}
func (*GetVideoLessonByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{10}
}
func (m *GetVideoLessonByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoLessonByIdResponse.Unmarshal(m, b)
}
func (m *GetVideoLessonByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoLessonByIdResponse.Marshal(b, m, deterministic)
}
func (dst *GetVideoLessonByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoLessonByIdResponse.Merge(dst, src)
}
func (m *GetVideoLessonByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetVideoLessonByIdResponse.Size(m)
}
func (m *GetVideoLessonByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoLessonByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoLessonByIdResponse proto.InternalMessageInfo

func (m *GetVideoLessonByIdResponse) GetLesson() *VideoLesson {
	if m != nil {
		return m.Lesson
	}
	return nil
}

// ----------------------------
// TEXT-LESSON (Type: 1)
// ----------------------------
type TextLesson struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextLesson) Reset()         { *m = TextLesson{} }
func (m *TextLesson) String() string { return proto.CompactTextString(m) }
func (*TextLesson) ProtoMessage()    {}
func (*TextLesson) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_4f4cae79985b64a1, []int{11}
}
func (m *TextLesson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextLesson.Unmarshal(m, b)
}
func (m *TextLesson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextLesson.Marshal(b, m, deterministic)
}
func (dst *TextLesson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextLesson.Merge(dst, src)
}
func (m *TextLesson) XXX_Size() int {
	return xxx_messageInfo_TextLesson.Size(m)
}
func (m *TextLesson) XXX_DiscardUnknown() {
	xxx_messageInfo_TextLesson.DiscardUnknown(m)
}

var xxx_messageInfo_TextLesson proto.InternalMessageInfo

func (m *TextLesson) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Lesson)(nil), "educonn.lesson.Lesson")
	proto.RegisterType((*LessonBase)(nil), "educonn.lesson.LessonBase")
	proto.RegisterType((*LessonStatistics)(nil), "educonn.lesson.LessonStatistics")
	proto.RegisterType((*CreateLesson)(nil), "educonn.lesson.CreateLesson")
	proto.RegisterType((*CreateLesson_Request)(nil), "educonn.lesson.CreateLesson.Request")
	proto.RegisterType((*CreateLesson_Response)(nil), "educonn.lesson.CreateLesson.Response")
	proto.RegisterType((*GetLesson)(nil), "educonn.lesson.GetLesson")
	proto.RegisterType((*GetLesson_ById)(nil), "educonn.lesson.GetLesson.ById")
	proto.RegisterType((*GetLesson_ById_Request)(nil), "educonn.lesson.GetLesson.ById.Request")
	proto.RegisterType((*GetLesson_ById_Response)(nil), "educonn.lesson.GetLesson.ById.Response")
	proto.RegisterType((*LessonCreatedEvent)(nil), "educonn.lesson.LessonCreatedEvent")
	proto.RegisterType((*VideoLesson)(nil), "educonn.lesson.VideoLesson")
	proto.RegisterType((*CreateVideoLessonRequest)(nil), "educonn.lesson.CreateVideoLessonRequest")
	proto.RegisterType((*CreateVideoLessonResponse)(nil), "educonn.lesson.CreateVideoLessonResponse")
	proto.RegisterType((*GetVideoLessonByIdRequest)(nil), "educonn.lesson.GetVideoLessonByIdRequest")
	proto.RegisterType((*GetVideoLessonByIdResponse)(nil), "educonn.lesson.GetVideoLessonByIdResponse")
	proto.RegisterType((*TextLesson)(nil), "educonn.lesson.TextLesson")
	proto.RegisterEnum("educonn.lesson.Type", Type_name, Type_value)
}

func init() { proto.RegisterFile("lesson/proto/lesson.proto", fileDescriptor_lesson_4f4cae79985b64a1) }

var fileDescriptor_lesson_4f4cae79985b64a1 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xae, 0x53, 0x3b, 0x8d, 0xa7, 0xff, 0x5f, 0x45, 0xa3, 0xaa, 0x72, 0x1c, 0x0e, 0x91, 0x45,
	0x21, 0xed, 0xc1, 0x15, 0xa9, 0x04, 0x88, 0x63, 0x69, 0x14, 0x45, 0x42, 0x2a, 0x2c, 0x51, 0x41,
	0x08, 0xa9, 0x72, 0xe2, 0x39, 0xac, 0x28, 0x76, 0xc8, 0x6e, 0x02, 0x79, 0x0f, 0xc4, 0x0b, 0xf0,
	0x2e, 0xbc, 0x03, 0x67, 0x5e, 0x04, 0x79, 0xd7, 0x76, 0x8c, 0x63, 0xd1, 0x40, 0xb9, 0x79, 0x76,
	0xbf, 0x99, 0xf9, 0xbe, 0x6f, 0x66, 0x65, 0x68, 0x5d, 0x93, 0x10, 0x71, 0x74, 0x32, 0x9d, 0xc5,
	0x32, 0x3e, 0xd1, 0x81, 0xaf, 0x02, 0xdc, 0xa3, 0x70, 0x3e, 0x89, 0xa3, 0xc8, 0xd7, 0xa7, 0xde,
	0x57, 0x03, 0xea, 0xcf, 0xd4, 0x27, 0xfa, 0x60, 0x8e, 0x03, 0x41, 0x8e, 0xd1, 0x31, 0xba, 0xbb,
	0x3d, 0xd7, 0xff, 0x15, 0xe9, 0x6b, 0xd4, 0x59, 0x20, 0x88, 0x29, 0x1c, 0x3e, 0x04, 0x4b, 0xc8,
	0x40, 0x0a, 0xa7, 0xa6, 0x12, 0x3a, 0xd5, 0x09, 0x2f, 0x65, 0x20, 0xb9, 0x90, 0x7c, 0x22, 0x98,
	0x86, 0xe3, 0x03, 0xb0, 0x16, 0x3c, 0xa4, 0xd8, 0xd9, 0x56, 0x79, 0xed, 0x72, 0xde, 0x65, 0x72,
	0xa9, 0x93, 0x99, 0x46, 0x7a, 0x9f, 0x0d, 0x80, 0x55, 0x7f, 0xdc, 0x83, 0x1a, 0x0f, 0x15, 0x4f,
	0x9b, 0xd5, 0x78, 0x88, 0x08, 0x66, 0x14, 0xbc, 0x27, 0x45, 0xc4, 0x66, 0xea, 0x1b, 0x3b, 0xb0,
	0x1b, 0x92, 0x98, 0xcc, 0xf8, 0x54, 0xf2, 0x38, 0x52, 0xbd, 0x6c, 0x56, 0x3c, 0xc2, 0x2e, 0x98,
	0x72, 0x39, 0x25, 0xc7, 0xec, 0x18, 0xdd, 0xbd, 0xde, 0x7e, 0x99, 0xc6, 0x68, 0x39, 0x25, 0xa6,
	0x10, 0x78, 0x00, 0xf5, 0xb9, 0xa0, 0xd9, 0x30, 0x74, 0x2c, 0x55, 0x26, 0x8d, 0xbc, 0x37, 0xd0,
	0x2c, 0x8b, 0xc4, 0x7d, 0xb0, 0xae, 0xf9, 0x3b, 0x12, 0x8a, 0xde, 0x36, 0xd3, 0x01, 0xba, 0xd0,
	0x08, 0xb9, 0xd0, 0x17, 0x35, 0x75, 0x91, 0xc7, 0x49, 0xc6, 0x82, 0xd3, 0x47, 0xa1, 0x38, 0x6e,
	0x33, 0x1d, 0x78, 0x3f, 0x0c, 0xf8, 0xef, 0xe9, 0x8c, 0x02, 0x49, 0xba, 0x85, 0xfb, 0xc5, 0x80,
	0x1d, 0x46, 0x1f, 0xe6, 0x24, 0xe4, 0x3f, 0x32, 0x00, 0x0b, 0x06, 0xd8, 0xa9, 0xd4, 0x7c, 0x38,
	0xd6, 0xa6, 0xc3, 0x71, 0x9f, 0x40, 0x83, 0x91, 0x98, 0xc6, 0x91, 0x20, 0xf4, 0xa1, 0xae, 0x81,
	0xe9, 0x16, 0x1d, 0x54, 0x2f, 0x05, 0x4b, 0x51, 0xde, 0x02, 0xec, 0x01, 0xc9, 0x54, 0x21, 0x07,
	0xf3, 0x6c, 0x39, 0x0c, 0xdd, 0xc3, 0x95, 0x50, 0x17, 0x1a, 0x1a, 0x39, 0xcc, 0xe4, 0xe6, 0xf1,
	0xad, 0xfa, 0x9e, 0x03, 0xea, 0x13, 0x6d, 0x71, 0xd8, 0x5f, 0x50, 0x24, 0xff, 0xb8, 0xca, 0x23,
	0xd8, 0x2d, 0xf8, 0xb1, 0x36, 0x15, 0x07, 0x76, 0x94, 0x43, 0xc3, 0x30, 0x1d, 0x4c, 0x16, 0x7a,
	0x17, 0xe0, 0xe8, 0xc6, 0x45, 0x3b, 0x53, 0xc9, 0xa7, 0x25, 0x12, 0xbf, 0x1d, 0x41, 0xc6, 0xe4,
	0x39, 0xb4, 0x2a, 0x0a, 0xa6, 0xe6, 0xfc, 0x55, 0xc5, 0xc7, 0xd0, 0x1a, 0x90, 0x2c, 0xdc, 0x24,
	0xa3, 0xc9, 0x38, 0xb6, 0xc1, 0xd6, 0xb0, 0x2b, 0xbe, 0x36, 0x17, 0xef, 0x05, 0xb8, 0x55, 0x99,
	0xb7, 0x21, 0x73, 0x07, 0x60, 0x44, 0x9f, 0x64, 0xb5, 0xcf, 0xc7, 0x6d, 0x30, 0x93, 0xc7, 0x8a,
	0x36, 0x58, 0x97, 0xc3, 0xf3, 0xfe, 0x45, 0x73, 0x0b, 0x1b, 0x60, 0x8e, 0xfa, 0xaf, 0x47, 0x4d,
	0xa3, 0xf7, 0xcd, 0x80, 0xff, 0xd3, 0x47, 0x4a, 0xb3, 0x05, 0x9f, 0x10, 0xbe, 0x82, 0xba, 0xf6,
	0x0a, 0xef, 0x96, 0x7b, 0x17, 0x1f, 0x9c, 0x9f, 0x8a, 0x75, 0x0f, 0x6f, 0x40, 0x69, 0x61, 0xde,
	0x16, 0xbe, 0x85, 0x9d, 0x01, 0xc9, 0x44, 0x2d, 0xde, 0x2b, 0xe7, 0xe4, 0x5b, 0xee, 0x27, 0xf7,
	0x79, 0xed, 0xfb, 0x37, 0xe2, 0xb2, 0xea, 0xbd, 0xef, 0x06, 0x60, 0xc1, 0x9b, 0x4c, 0xcd, 0x55,
	0xae, 0xa6, 0x5b, 0xcd, 0x73, 0x7d, 0xc5, 0xdc, 0xa3, 0x0d, 0x90, 0xb9, 0xaa, 0xf1, 0x4a, 0xd5,
	0x51, 0x05, 0xdb, 0xea, 0x0d, 0x71, 0x8f, 0x37, 0x81, 0x66, 0x3d, 0xc6, 0x75, 0xf5, 0x73, 0x3a,
	0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xcc, 0xf6, 0xa4, 0xb9, 0x06, 0x00, 0x00,
}
