// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transcode.proto

package educonn_transcode

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ----------------------------
// TRANSCODE RESOURCE
// ----------------------------
type TranscodeDetails struct {
	JobId                string           `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	PipelineId           string           `protobuf:"bytes,2,opt,name=pipelineId,proto3" json:"pipelineId,omitempty"`
	InputKey             string           `protobuf:"bytes,3,opt,name=inputKey,proto3" json:"inputKey,omitempty"`
	OutputKeyPrefix      string           `protobuf:"bytes,4,opt,name=outputKeyPrefix,proto3" json:"outputKeyPrefix,omitempty"`
	OutputKey            string           `protobuf:"bytes,5,opt,name=outputKey,proto3" json:"outputKey,omitempty"`
	Status               *TranscodeStatus `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TranscodeDetails) Reset()         { *m = TranscodeDetails{} }
func (m *TranscodeDetails) String() string { return proto.CompactTextString(m) }
func (*TranscodeDetails) ProtoMessage()    {}
func (*TranscodeDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_transcode_6c0ed2b9f697dc3d, []int{0}
}
func (m *TranscodeDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodeDetails.Unmarshal(m, b)
}
func (m *TranscodeDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodeDetails.Marshal(b, m, deterministic)
}
func (dst *TranscodeDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodeDetails.Merge(dst, src)
}
func (m *TranscodeDetails) XXX_Size() int {
	return xxx_messageInfo_TranscodeDetails.Size(m)
}
func (m *TranscodeDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodeDetails.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodeDetails proto.InternalMessageInfo

func (m *TranscodeDetails) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *TranscodeDetails) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *TranscodeDetails) GetInputKey() string {
	if m != nil {
		return m.InputKey
	}
	return ""
}

func (m *TranscodeDetails) GetOutputKeyPrefix() string {
	if m != nil {
		return m.OutputKeyPrefix
	}
	return ""
}

func (m *TranscodeDetails) GetOutputKey() string {
	if m != nil {
		return m.OutputKey
	}
	return ""
}

func (m *TranscodeDetails) GetStatus() *TranscodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type TranscodeStatus struct {
	Started              bool     `protobuf:"varint,4,opt,name=started,proto3" json:"started,omitempty"`
	Completed            bool     `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Error                bool     `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorMessages        []string `protobuf:"bytes,3,rep,name=errorMessages,proto3" json:"errorMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranscodeStatus) Reset()         { *m = TranscodeStatus{} }
func (m *TranscodeStatus) String() string { return proto.CompactTextString(m) }
func (*TranscodeStatus) ProtoMessage()    {}
func (*TranscodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_transcode_6c0ed2b9f697dc3d, []int{1}
}
func (m *TranscodeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodeStatus.Unmarshal(m, b)
}
func (m *TranscodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodeStatus.Marshal(b, m, deterministic)
}
func (dst *TranscodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodeStatus.Merge(dst, src)
}
func (m *TranscodeStatus) XXX_Size() int {
	return xxx_messageInfo_TranscodeStatus.Size(m)
}
func (m *TranscodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodeStatus proto.InternalMessageInfo

func (m *TranscodeStatus) GetStarted() bool {
	if m != nil {
		return m.Started
	}
	return false
}

func (m *TranscodeStatus) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *TranscodeStatus) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *TranscodeStatus) GetErrorMessages() []string {
	if m != nil {
		return m.ErrorMessages
	}
	return nil
}

// ----------------------------
// EVENTS
// ----------------------------
type TranscodingCompletedEvent struct {
	Transcode            *TranscodeDetails `protobuf:"bytes,1,opt,name=transcode,proto3" json:"transcode,omitempty"`
	VideoId              string            `protobuf:"bytes,2,opt,name=videoId,proto3" json:"videoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TranscodingCompletedEvent) Reset()         { *m = TranscodingCompletedEvent{} }
func (m *TranscodingCompletedEvent) String() string { return proto.CompactTextString(m) }
func (*TranscodingCompletedEvent) ProtoMessage()    {}
func (*TranscodingCompletedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_transcode_6c0ed2b9f697dc3d, []int{2}
}
func (m *TranscodingCompletedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodingCompletedEvent.Unmarshal(m, b)
}
func (m *TranscodingCompletedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodingCompletedEvent.Marshal(b, m, deterministic)
}
func (dst *TranscodingCompletedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodingCompletedEvent.Merge(dst, src)
}
func (m *TranscodingCompletedEvent) XXX_Size() int {
	return xxx_messageInfo_TranscodingCompletedEvent.Size(m)
}
func (m *TranscodingCompletedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodingCompletedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodingCompletedEvent proto.InternalMessageInfo

func (m *TranscodingCompletedEvent) GetTranscode() *TranscodeDetails {
	if m != nil {
		return m.Transcode
	}
	return nil
}

func (m *TranscodingCompletedEvent) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

type TranscodingFailedEvent struct {
	Transcode            *TranscodeDetails `protobuf:"bytes,1,opt,name=transcode,proto3" json:"transcode,omitempty"`
	VideoId              string            `protobuf:"bytes,2,opt,name=videoId,proto3" json:"videoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TranscodingFailedEvent) Reset()         { *m = TranscodingFailedEvent{} }
func (m *TranscodingFailedEvent) String() string { return proto.CompactTextString(m) }
func (*TranscodingFailedEvent) ProtoMessage()    {}
func (*TranscodingFailedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_transcode_6c0ed2b9f697dc3d, []int{3}
}
func (m *TranscodingFailedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranscodingFailedEvent.Unmarshal(m, b)
}
func (m *TranscodingFailedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranscodingFailedEvent.Marshal(b, m, deterministic)
}
func (dst *TranscodingFailedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscodingFailedEvent.Merge(dst, src)
}
func (m *TranscodingFailedEvent) XXX_Size() int {
	return xxx_messageInfo_TranscodingFailedEvent.Size(m)
}
func (m *TranscodingFailedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscodingFailedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TranscodingFailedEvent proto.InternalMessageInfo

func (m *TranscodingFailedEvent) GetTranscode() *TranscodeDetails {
	if m != nil {
		return m.Transcode
	}
	return nil
}

func (m *TranscodingFailedEvent) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

// ----------------------------
// REQUESTS AND RESPONSES
// ----------------------------
type CreateJobRequest struct {
	Job                  *TranscodeDetails `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	VideoId              string            `protobuf:"bytes,2,opt,name=videoId,proto3" json:"videoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transcode_6c0ed2b9f697dc3d, []int{4}
}
func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (dst *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(dst, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetJob() *TranscodeDetails {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *CreateJobRequest) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

type CreateJobResponse struct {
	Job                  *TranscodeDetails `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transcode_6c0ed2b9f697dc3d, []int{5}
}
func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (dst *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(dst, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetJob() *TranscodeDetails {
	if m != nil {
		return m.Job
	}
	return nil
}

// ----------------------------
// MISC
// ----------------------------
type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_transcode_6c0ed2b9f697dc3d, []int{6}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*TranscodeDetails)(nil), "educonn.transcode.TranscodeDetails")
	proto.RegisterType((*TranscodeStatus)(nil), "educonn.transcode.TranscodeStatus")
	proto.RegisterType((*TranscodingCompletedEvent)(nil), "educonn.transcode.TranscodingCompletedEvent")
	proto.RegisterType((*TranscodingFailedEvent)(nil), "educonn.transcode.TranscodingFailedEvent")
	proto.RegisterType((*CreateJobRequest)(nil), "educonn.transcode.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "educonn.transcode.CreateJobResponse")
	proto.RegisterType((*Error)(nil), "educonn.transcode.Error")
}

func init() { proto.RegisterFile("transcode.proto", fileDescriptor_transcode_6c0ed2b9f697dc3d) }

var fileDescriptor_transcode_6c0ed2b9f697dc3d = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4f, 0xeb, 0xd3, 0x40,
	0x14, 0x34, 0xe6, 0x97, 0xda, 0xbc, 0x22, 0xfd, 0x75, 0x11, 0x59, 0x8b, 0x48, 0x88, 0x3d, 0xe4,
	0x94, 0x43, 0xc5, 0x8b, 0xe0, 0x41, 0x6a, 0x85, 0x56, 0x04, 0x59, 0x3d, 0x78, 0xcd, 0x9f, 0x67,
	0xd9, 0x12, 0x77, 0xe3, 0xee, 0xa6, 0xd4, 0x0f, 0xe0, 0x77, 0xf5, 0x63, 0x48, 0x36, 0xcd, 0x36,
	0x56, 0x29, 0xe8, 0xc1, 0x5b, 0x66, 0xe6, 0xed, 0xce, 0xcc, 0x5b, 0x02, 0x53, 0xa3, 0x32, 0xa1,
	0x0b, 0x59, 0x62, 0x5a, 0x2b, 0x69, 0x24, 0x99, 0x61, 0xd9, 0x14, 0x52, 0x88, 0xd4, 0x09, 0xf1,
	0x0f, 0x0f, 0x6e, 0x3f, 0xf6, 0xe8, 0x35, 0x9a, 0x8c, 0x57, 0x9a, 0x3c, 0x80, 0x60, 0x2f, 0xf3,
	0x4d, 0x49, 0xbd, 0xc8, 0x4b, 0x42, 0xd6, 0x01, 0xf2, 0x04, 0xa0, 0xe6, 0x35, 0x56, 0x5c, 0xe0,
	0xa6, 0xa4, 0x77, 0xad, 0x34, 0x60, 0xc8, 0x1c, 0xc6, 0x5c, 0xd4, 0x8d, 0x79, 0x8b, 0xdf, 0xa8,
	0x6f, 0x55, 0x87, 0x49, 0x02, 0x53, 0xd9, 0x98, 0x0e, 0xbc, 0x57, 0xf8, 0x99, 0x1f, 0xe9, 0x8d,
	0x1d, 0xb9, 0xa4, 0xc9, 0x63, 0x08, 0x1d, 0x45, 0x03, 0x3b, 0x73, 0x26, 0xc8, 0x0b, 0x18, 0x69,
	0x93, 0x99, 0x46, 0xd3, 0x51, 0xe4, 0x25, 0x93, 0x65, 0x9c, 0xfe, 0x56, 0x29, 0x75, 0x75, 0x3e,
	0xd8, 0x49, 0x76, 0x3a, 0x11, 0x7f, 0xf7, 0x60, 0x7a, 0xa1, 0x11, 0x0a, 0xf7, 0xb4, 0xc9, 0x94,
	0xc1, 0xd2, 0xe6, 0x19, 0xb3, 0x1e, 0xb6, 0x39, 0x0a, 0xf9, 0xa5, 0xae, 0xb0, 0xd5, 0x3c, 0xab,
	0x9d, 0x89, 0x76, 0x43, 0xa8, 0x94, 0x54, 0x76, 0x0d, 0x63, 0xd6, 0x01, 0xb2, 0x80, 0xfb, 0xf6,
	0xe3, 0x1d, 0x6a, 0x9d, 0xed, 0x50, 0x53, 0x3f, 0xf2, 0x93, 0x90, 0xfd, 0x4a, 0xc6, 0x47, 0x78,
	0xd4, 0xc7, 0xe0, 0x62, 0xb7, 0xea, 0xef, 0x5c, 0x1f, 0x50, 0x18, 0xf2, 0x0a, 0x42, 0xd7, 0xc4,
	0xda, 0x4e, 0x96, 0x4f, 0xaf, 0x75, 0x3c, 0x3d, 0x19, 0x3b, 0x9f, 0x6a, 0x3b, 0x1d, 0x78, 0x89,
	0xd2, 0x3d, 0x52, 0x0f, 0xe3, 0x06, 0x1e, 0x0e, 0x9c, 0xdf, 0x64, 0xbc, 0xfa, 0x2f, 0xb6, 0x05,
	0xdc, 0xae, 0x14, 0x66, 0x06, 0xb7, 0x32, 0x67, 0xf8, 0xb5, 0x41, 0x6d, 0xc8, 0x73, 0xf0, 0xf7,
	0x32, 0xff, 0x1b, 0xab, 0x76, 0xfe, 0x8a, 0xc9, 0x16, 0x66, 0x03, 0x13, 0x5d, 0x4b, 0xa1, 0xf1,
	0x1f, 0x5d, 0xe2, 0x97, 0x10, 0xac, 0xed, 0x83, 0x12, 0xb8, 0x71, 0x1b, 0x09, 0x98, 0xfd, 0x26,
	0x11, 0x4c, 0x4a, 0xd4, 0x85, 0xe2, 0xb5, 0xe1, 0x52, 0x9c, 0x62, 0x0c, 0xa9, 0x25, 0x42, 0xe8,
	0xee, 0x25, 0x9f, 0x20, 0x74, 0xb9, 0xc8, 0x9f, 0x22, 0x5c, 0xae, 0x66, 0xbe, 0xb8, 0x3e, 0xd4,
	0x55, 0x8b, 0xef, 0xe4, 0x23, 0xfb, 0x53, 0x3f, 0xfb, 0x19, 0x00, 0x00, 0xff, 0xff, 0xff, 0x66,
	0x2c, 0x27, 0xe7, 0x03, 0x00, 0x00,
}
