// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-api/proto/user_api.proto

package educonn_user_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "github.com/lukasjarosch/educonn-platform/user/proto"
import proto2 "github.com/lukasjarosch/educonn-platform/video/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	User                 *proto1.UserDetails `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_api_bd6779c3b2469b79, []int{0}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUser() *proto1.UserDetails {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResponse struct {
	User                 *proto1.UserDetails `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_api_bd6779c3b2469b79, []int{1}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetUser() *proto1.UserDetails {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_api_bd6779c3b2469b79, []int{2}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_api_bd6779c3b2469b79, []int{3}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_api_bd6779c3b2469b79, []int{4}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_api_bd6779c3b2469b79, []int{5}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VideoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoRequest) Reset()         { *m = VideoRequest{} }
func (m *VideoRequest) String() string { return proto.CompactTextString(m) }
func (*VideoRequest) ProtoMessage()    {}
func (*VideoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_api_bd6779c3b2469b79, []int{6}
}
func (m *VideoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoRequest.Unmarshal(m, b)
}
func (m *VideoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoRequest.Marshal(b, m, deterministic)
}
func (dst *VideoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoRequest.Merge(dst, src)
}
func (m *VideoRequest) XXX_Size() int {
	return xxx_messageInfo_VideoRequest.Size(m)
}
func (m *VideoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VideoRequest proto.InternalMessageInfo

type VideoResponse struct {
	Videos               []*proto2.VideoDetails `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VideoResponse) Reset()         { *m = VideoResponse{} }
func (m *VideoResponse) String() string { return proto.CompactTextString(m) }
func (*VideoResponse) ProtoMessage()    {}
func (*VideoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_api_bd6779c3b2469b79, []int{7}
}
func (m *VideoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoResponse.Unmarshal(m, b)
}
func (m *VideoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoResponse.Marshal(b, m, deterministic)
}
func (dst *VideoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoResponse.Merge(dst, src)
}
func (m *VideoResponse) XXX_Size() int {
	return xxx_messageInfo_VideoResponse.Size(m)
}
func (m *VideoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VideoResponse proto.InternalMessageInfo

func (m *VideoResponse) GetVideos() []*proto2.VideoDetails {
	if m != nil {
		return m.Videos
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "educonn.user_api.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "educonn.user_api.CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "educonn.user_api.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "educonn.user_api.DeleteResponse")
	proto.RegisterType((*LoginRequest)(nil), "educonn.user_api.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "educonn.user_api.LoginResponse")
	proto.RegisterType((*VideoRequest)(nil), "educonn.user_api.VideoRequest")
	proto.RegisterType((*VideoResponse)(nil), "educonn.user_api.VideoResponse")
}

func init() {
	proto.RegisterFile("user-api/proto/user_api.proto", fileDescriptor_user_api_bd6779c3b2469b79)
}

var fileDescriptor_user_api_bd6779c3b2469b79 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcb, 0x4f, 0xc2, 0x40,
	0x10, 0xc6, 0x01, 0xa5, 0xea, 0x40, 0x09, 0xd9, 0xa0, 0x62, 0x8d, 0x42, 0x36, 0x31, 0x72, 0xa1,
	0x24, 0x70, 0xf7, 0x11, 0xb9, 0xf8, 0xba, 0x90, 0xe8, 0xd5, 0xac, 0x76, 0x62, 0x36, 0x62, 0x77,
	0xed, 0x16, 0xfd, 0xf7, 0xfc, 0xd3, 0xcc, 0x3e, 0x8a, 0x2d, 0x96, 0x83, 0xb7, 0x7e, 0x3b, 0xdf,
	0x7c, 0xb3, 0xfb, 0x9b, 0xc2, 0xd1, 0x42, 0x61, 0x32, 0x64, 0x92, 0x8f, 0x64, 0x22, 0x52, 0x31,
	0xd2, 0xf2, 0x89, 0x49, 0x1e, 0x1a, 0x49, 0xda, 0x18, 0x2d, 0x5e, 0x44, 0x1c, 0x87, 0xd9, 0x79,
	0xb0, 0xab, 0xbf, 0x72, 0x66, 0x6b, 0x0c, 0xf6, 0x3f, 0x79, 0x84, 0xc2, 0x9d, 0x9b, 0x6f, 0x5b,
	0xa0, 0x67, 0xe0, 0x5f, 0x25, 0xc8, 0x52, 0x9c, 0xe1, 0xc7, 0x02, 0x55, 0x4a, 0x86, 0xb0, 0xa9,
	0xfb, 0xba, 0xd5, 0x7e, 0x75, 0xd0, 0x18, 0x1f, 0x84, 0xf9, 0x09, 0xe1, 0x83, 0xc2, 0x64, 0x8a,
	0x29, 0xe3, 0x73, 0x35, 0x33, 0x36, 0x7a, 0x0e, 0xad, 0xac, 0x5f, 0x49, 0x11, 0x2b, 0xfc, 0x6f,
	0xc0, 0x29, 0xf8, 0x53, 0x9c, 0xe3, 0xef, 0x05, 0xf6, 0xc0, 0xd3, 0x85, 0xeb, 0xc8, 0x24, 0xec,
	0xcc, 0x9c, 0xa2, 0x6d, 0x68, 0x65, 0x46, 0x3b, 0x89, 0x5e, 0x40, 0xf3, 0x4e, 0xbc, 0xf2, 0x38,
	0xeb, 0xec, 0x40, 0x1d, 0xdf, 0x19, 0x9f, 0xbb, 0x46, 0x2b, 0x48, 0x00, 0xdb, 0x92, 0x29, 0xf5,
	0x25, 0x92, 0xa8, 0x5b, 0x33, 0x85, 0xa5, 0xa6, 0x27, 0xe0, 0xbb, 0x04, 0x77, 0xf9, 0x0e, 0xd4,
	0x53, 0xf1, 0x86, 0xb1, 0x73, 0x5a, 0x41, 0x5b, 0xd0, 0x7c, 0xd4, 0xcc, 0xdc, 0x20, 0x3a, 0x05,
	0xdf, 0x69, 0xd7, 0x36, 0x01, 0xcf, 0x40, 0x55, 0xdd, 0x6a, 0x7f, 0x63, 0xd0, 0x18, 0x1f, 0x2e,
	0x5f, 0x6d, 0x59, 0x1b, 0x77, 0xf6, 0x6e, 0x67, 0x1d, 0x7f, 0xd7, 0x60, 0x4b, 0xf3, 0xb8, 0x94,
	0x9c, 0xdc, 0x83, 0x67, 0x31, 0x92, 0x5e, 0xb8, 0xba, 0xd3, 0xb0, 0xb0, 0xa0, 0xa0, 0xbf, 0xde,
	0xe0, 0xb8, 0x54, 0x74, 0x9c, 0x65, 0x55, 0x16, 0x57, 0xc0, 0x5d, 0x16, 0xb7, 0x82, 0xb9, 0x42,
	0x6e, 0xa0, 0x6e, 0x30, 0x91, 0xe3, 0xbf, 0xe6, 0xfc, 0x06, 0x82, 0xde, 0xda, 0xfa, 0x32, 0xeb,
	0x16, 0x3c, 0x43, 0x43, 0x95, 0x85, 0xe5, 0x29, 0x97, 0x85, 0x15, 0xa8, 0xd3, 0xca, 0xb3, 0x67,
	0x7e, 0xe2, 0xc9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x9e, 0x89, 0x2d, 0x27, 0x03, 0x00,
	0x00,
}
