// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: lesson-api.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	lesson-api.proto

It has these top-level messages:
	Error
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for LessonApi service

type LessonApiClient interface {
}

type lessonApiClient struct {
	c           client.Client
	serviceName string
}

func NewLessonApiClient(serviceName string, c client.Client) LessonApiClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "educonn.lesson.api"
	}
	return &lessonApiClient{
		c:           c,
		serviceName: serviceName,
	}
}

// Server API for LessonApi service

type LessonApiHandler interface {
}

func RegisterLessonApiHandler(s server.Server, hdlr LessonApiHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&LessonApi{hdlr}, opts...))
}

type LessonApi struct {
	LessonApiHandler
}
