// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lesson-api.proto

package proto // import "github.com/lukasjarosch/educonn-platform/lesson-api/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ----------------------------
// MISC
// ----------------------------
type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_api_c33296b74a670e1c, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "educonn.lesson.api.Error")
}

func init() { proto.RegisterFile("lesson-api.proto", fileDescriptor_lesson_api_c33296b74a670e1c) }

var fileDescriptor_lesson_api_c33296b74a670e1c = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x31, 0x0b, 0xc2, 0x30,
	0x14, 0x84, 0xa9, 0x58, 0xa1, 0xe9, 0x22, 0x99, 0x3a, 0x16, 0xa7, 0x2e, 0x4d, 0x40, 0x27, 0x11,
	0x07, 0x05, 0x37, 0xa7, 0x8e, 0x6e, 0x69, 0x1a, 0x6d, 0xb4, 0xcd, 0x7b, 0xbc, 0x24, 0xff, 0x5f,
	0x88, 0x82, 0x4e, 0x77, 0xdc, 0xc1, 0xdd, 0xc7, 0xd6, 0x93, 0xf1, 0x1e, 0x5c, 0xab, 0xd0, 0x0a,
	0x24, 0x08, 0xc0, 0xb9, 0x19, 0xa2, 0x06, 0xe7, 0xc4, 0xa7, 0x11, 0x0a, 0xed, 0xe6, 0xc8, 0xf2,
	0x0b, 0x11, 0x10, 0xe7, 0x6c, 0xa9, 0x61, 0x30, 0x55, 0x56, 0x67, 0x4d, 0xde, 0x25, 0xcf, 0x6b,
	0x56, 0x0e, 0xc6, 0x6b, 0xb2, 0x18, 0x2c, 0xb8, 0x6a, 0x51, 0x67, 0x4d, 0xd1, 0xfd, 0x47, 0xdb,
	0x92, 0x15, 0xd7, 0x34, 0x76, 0x42, 0x7b, 0x3e, 0xdc, 0xf6, 0x0f, 0x1b, 0xc6, 0xd8, 0x0b, 0x0d,
	0xb3, 0x9c, 0xe2, 0x4b, 0xf9, 0xa7, 0x22, 0xf0, 0x7a, 0x94, 0xdf, 0xe7, 0x16, 0x27, 0x15, 0xee,
	0x40, 0xb3, 0xfc, 0xc1, 0xc9, 0x04, 0xd7, 0xaf, 0x92, 0xec, 0xde, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x35, 0x64, 0x1d, 0xbd, 0xb7, 0x00, 0x00, 0x00,
}
