// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package proto // import "github.com/lukasjarosch/educonn-platform/mail/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mail_9fea8ba1a69f498d, []int{0}
}
func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (dst *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(dst, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EmailRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_mail_9fea8ba1a69f498d, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EmailRequest)(nil), "educonn.mail.EmailRequest")
	proto.RegisterType((*Response)(nil), "educonn.mail.Response")
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor_mail_9fea8ba1a69f498d) }

var fileDescriptor_mail_9fea8ba1a69f498d = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x4f, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0x43, 0xf8, 0x3a, 0x55, 0x0c, 0x1e, 0x90, 0xd5, 0x09, 0x75, 0x62, 0xc1, 0x96, 0xa8,
	0x58, 0x18, 0x41, 0xfc, 0x81, 0xb0, 0xb1, 0x39, 0xee, 0xa5, 0x4d, 0x88, 0x7d, 0xc1, 0x67, 0xff,
	0x7f, 0x64, 0x93, 0x48, 0x61, 0xba, 0xf7, 0xa1, 0x77, 0xf7, 0x0e, 0xc0, 0x99, 0x7e, 0x54, 0x53,
	0xa0, 0x48, 0x62, 0x8b, 0xc7, 0x64, 0xc9, 0x7b, 0x95, 0xb5, 0x7d, 0x07, 0xdb, 0x8f, 0x0c, 0x1a,
	0xfc, 0x49, 0xc8, 0x51, 0x08, 0xa8, 0xbb, 0x40, 0x4e, 0x6e, 0x1e, 0x36, 0x8f, 0xb7, 0x4d, 0xc1,
	0xe2, 0x0e, 0xaa, 0x48, 0xb2, 0x2a, 0x4a, 0x15, 0x49, 0x48, 0xb8, 0xe6, 0xd4, 0x0e, 0x68, 0xa3,
	0xbc, 0x28, 0xe2, 0x42, 0xb3, 0xe3, 0x90, 0xd9, 0x9c, 0x50, 0xd6, 0x7f, 0xce, 0x4c, 0xf7, 0x00,
	0x37, 0x0d, 0xf2, 0x44, 0x9e, 0xf1, 0xf9, 0x1d, 0x2e, 0xcb, 0x4d, 0xf1, 0x0a, 0xf5, 0x27, 0xfa,
	0xa3, 0xd8, 0xa9, 0x75, 0x27, 0xb5, 0x2e, 0xb4, 0xbb, 0xff, 0xef, 0x2d, 0x4b, 0xde, 0x5e, 0xbe,
	0x0e, 0xa7, 0x3e, 0x9e, 0x53, 0xab, 0x2c, 0x39, 0x3d, 0xa6, 0x6f, 0xc3, 0x83, 0x09, 0xc4, 0xf6,
	0xac, 0xe7, 0xc0, 0xd3, 0x34, 0x9a, 0xd8, 0x51, 0x70, 0x3a, 0x27, 0x75, 0xf9, 0xbe, 0xbd, 0x2a,
	0xe3, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x46, 0xe4, 0xae, 0xeb, 0x12, 0x01, 0x00, 0x00,
}
