// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video.proto

package proto // import "github.com/lukasjarosch/educonn-platform/mail/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ----------------------------
// VIDEO RESOURCE
// ----------------------------
type VideoDetails struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string            `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string            `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags                 []string          `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Status               *VideoStatus      `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Statistics           *VideoStatistics  `protobuf:"bytes,6,opt,name=statistics,proto3" json:"statistics,omitempty"`
	Thumbnails           []*VideoThumbnail `protobuf:"bytes,7,rep,name=thumbnails,proto3" json:"thumbnails,omitempty"`
	Storage              *VideoStorage     `protobuf:"bytes,8,opt,name=storage,proto3" json:"storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VideoDetails) Reset()         { *m = VideoDetails{} }
func (m *VideoDetails) String() string { return proto.CompactTextString(m) }
func (*VideoDetails) ProtoMessage()    {}
func (*VideoDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{0}
}
func (m *VideoDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoDetails.Unmarshal(m, b)
}
func (m *VideoDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoDetails.Marshal(b, m, deterministic)
}
func (dst *VideoDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoDetails.Merge(dst, src)
}
func (m *VideoDetails) XXX_Size() int {
	return xxx_messageInfo_VideoDetails.Size(m)
}
func (m *VideoDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoDetails.DiscardUnknown(m)
}

var xxx_messageInfo_VideoDetails proto.InternalMessageInfo

func (m *VideoDetails) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VideoDetails) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VideoDetails) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *VideoDetails) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *VideoDetails) GetStatus() *VideoStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *VideoDetails) GetStatistics() *VideoStatistics {
	if m != nil {
		return m.Statistics
	}
	return nil
}

func (m *VideoDetails) GetThumbnails() []*VideoThumbnail {
	if m != nil {
		return m.Thumbnails
	}
	return nil
}

func (m *VideoDetails) GetStorage() *VideoStorage {
	if m != nil {
		return m.Storage
	}
	return nil
}

type VideoStorage struct {
	RawKey               string   `protobuf:"bytes,1,opt,name=rawKey,proto3" json:"rawKey,omitempty"`
	TranscodedKey        string   `protobuf:"bytes,2,opt,name=transcodedKey,proto3" json:"transcodedKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoStorage) Reset()         { *m = VideoStorage{} }
func (m *VideoStorage) String() string { return proto.CompactTextString(m) }
func (*VideoStorage) ProtoMessage()    {}
func (*VideoStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{1}
}
func (m *VideoStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoStorage.Unmarshal(m, b)
}
func (m *VideoStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoStorage.Marshal(b, m, deterministic)
}
func (dst *VideoStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoStorage.Merge(dst, src)
}
func (m *VideoStorage) XXX_Size() int {
	return xxx_messageInfo_VideoStorage.Size(m)
}
func (m *VideoStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoStorage.DiscardUnknown(m)
}

var xxx_messageInfo_VideoStorage proto.InternalMessageInfo

func (m *VideoStorage) GetRawKey() string {
	if m != nil {
		return m.RawKey
	}
	return ""
}

func (m *VideoStorage) GetTranscodedKey() string {
	if m != nil {
		return m.TranscodedKey
	}
	return ""
}

type VideoStatus struct {
	Completed            bool     `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Warning              bool     `protobuf:"varint,2,opt,name=warning,proto3" json:"warning,omitempty"`
	Error                bool     `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	WarningMessages      []string `protobuf:"bytes,4,rep,name=warningMessages,proto3" json:"warningMessages,omitempty"`
	ErrorMessages        []string `protobuf:"bytes,5,rep,name=errorMessages,proto3" json:"errorMessages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoStatus) Reset()         { *m = VideoStatus{} }
func (m *VideoStatus) String() string { return proto.CompactTextString(m) }
func (*VideoStatus) ProtoMessage()    {}
func (*VideoStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{2}
}
func (m *VideoStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoStatus.Unmarshal(m, b)
}
func (m *VideoStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoStatus.Marshal(b, m, deterministic)
}
func (dst *VideoStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoStatus.Merge(dst, src)
}
func (m *VideoStatus) XXX_Size() int {
	return xxx_messageInfo_VideoStatus.Size(m)
}
func (m *VideoStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoStatus.DiscardUnknown(m)
}

var xxx_messageInfo_VideoStatus proto.InternalMessageInfo

func (m *VideoStatus) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *VideoStatus) GetWarning() bool {
	if m != nil {
		return m.Warning
	}
	return false
}

func (m *VideoStatus) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *VideoStatus) GetWarningMessages() []string {
	if m != nil {
		return m.WarningMessages
	}
	return nil
}

func (m *VideoStatus) GetErrorMessages() []string {
	if m != nil {
		return m.ErrorMessages
	}
	return nil
}

type VideoStatistics struct {
	ViewCount            int64    `protobuf:"varint,1,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
	LikeCount            int64    `protobuf:"varint,2,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	DislikeCound         int64    `protobuf:"varint,3,opt,name=dislikeCound,proto3" json:"dislikeCound,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoStatistics) Reset()         { *m = VideoStatistics{} }
func (m *VideoStatistics) String() string { return proto.CompactTextString(m) }
func (*VideoStatistics) ProtoMessage()    {}
func (*VideoStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{3}
}
func (m *VideoStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoStatistics.Unmarshal(m, b)
}
func (m *VideoStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoStatistics.Marshal(b, m, deterministic)
}
func (dst *VideoStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoStatistics.Merge(dst, src)
}
func (m *VideoStatistics) XXX_Size() int {
	return xxx_messageInfo_VideoStatistics.Size(m)
}
func (m *VideoStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_VideoStatistics proto.InternalMessageInfo

func (m *VideoStatistics) GetViewCount() int64 {
	if m != nil {
		return m.ViewCount
	}
	return 0
}

func (m *VideoStatistics) GetLikeCount() int64 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *VideoStatistics) GetDislikeCound() int64 {
	if m != nil {
		return m.DislikeCound
	}
	return 0
}

type VideoThumbnail struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width                string   `protobuf:"bytes,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               string   `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoThumbnail) Reset()         { *m = VideoThumbnail{} }
func (m *VideoThumbnail) String() string { return proto.CompactTextString(m) }
func (*VideoThumbnail) ProtoMessage()    {}
func (*VideoThumbnail) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{4}
}
func (m *VideoThumbnail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoThumbnail.Unmarshal(m, b)
}
func (m *VideoThumbnail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoThumbnail.Marshal(b, m, deterministic)
}
func (dst *VideoThumbnail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoThumbnail.Merge(dst, src)
}
func (m *VideoThumbnail) XXX_Size() int {
	return xxx_messageInfo_VideoThumbnail.Size(m)
}
func (m *VideoThumbnail) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoThumbnail.DiscardUnknown(m)
}

var xxx_messageInfo_VideoThumbnail proto.InternalMessageInfo

func (m *VideoThumbnail) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *VideoThumbnail) GetWidth() string {
	if m != nil {
		return m.Width
	}
	return ""
}

func (m *VideoThumbnail) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

// ----------------------------
// EVENTS
// ----------------------------
type VideoCreatedEvent struct {
	Video                *VideoDetails `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	UserId               string        `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VideoCreatedEvent) Reset()         { *m = VideoCreatedEvent{} }
func (m *VideoCreatedEvent) String() string { return proto.CompactTextString(m) }
func (*VideoCreatedEvent) ProtoMessage()    {}
func (*VideoCreatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{5}
}
func (m *VideoCreatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoCreatedEvent.Unmarshal(m, b)
}
func (m *VideoCreatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoCreatedEvent.Marshal(b, m, deterministic)
}
func (dst *VideoCreatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoCreatedEvent.Merge(dst, src)
}
func (m *VideoCreatedEvent) XXX_Size() int {
	return xxx_messageInfo_VideoCreatedEvent.Size(m)
}
func (m *VideoCreatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoCreatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_VideoCreatedEvent proto.InternalMessageInfo

func (m *VideoCreatedEvent) GetVideo() *VideoDetails {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *VideoCreatedEvent) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateVideoRequest struct {
	Video                *VideoDetails `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateVideoRequest) Reset()         { *m = CreateVideoRequest{} }
func (m *CreateVideoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVideoRequest) ProtoMessage()    {}
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{6}
}
func (m *CreateVideoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVideoRequest.Unmarshal(m, b)
}
func (m *CreateVideoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVideoRequest.Marshal(b, m, deterministic)
}
func (dst *CreateVideoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVideoRequest.Merge(dst, src)
}
func (m *CreateVideoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVideoRequest.Size(m)
}
func (m *CreateVideoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVideoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVideoRequest proto.InternalMessageInfo

func (m *CreateVideoRequest) GetVideo() *VideoDetails {
	if m != nil {
		return m.Video
	}
	return nil
}

type CreateVideoResponse struct {
	Video                *VideoDetails `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	Errors               []*Error      `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateVideoResponse) Reset()         { *m = CreateVideoResponse{} }
func (m *CreateVideoResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVideoResponse) ProtoMessage()    {}
func (*CreateVideoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{7}
}
func (m *CreateVideoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVideoResponse.Unmarshal(m, b)
}
func (m *CreateVideoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVideoResponse.Marshal(b, m, deterministic)
}
func (dst *CreateVideoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVideoResponse.Merge(dst, src)
}
func (m *CreateVideoResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVideoResponse.Size(m)
}
func (m *CreateVideoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVideoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVideoResponse proto.InternalMessageInfo

func (m *CreateVideoResponse) GetVideo() *VideoDetails {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *CreateVideoResponse) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type GetVideoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoRequest) Reset()         { *m = GetVideoRequest{} }
func (m *GetVideoRequest) String() string { return proto.CompactTextString(m) }
func (*GetVideoRequest) ProtoMessage()    {}
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{8}
}
func (m *GetVideoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoRequest.Unmarshal(m, b)
}
func (m *GetVideoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoRequest.Marshal(b, m, deterministic)
}
func (dst *GetVideoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoRequest.Merge(dst, src)
}
func (m *GetVideoRequest) XXX_Size() int {
	return xxx_messageInfo_GetVideoRequest.Size(m)
}
func (m *GetVideoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoRequest proto.InternalMessageInfo

func (m *GetVideoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetVideoResponse struct {
	Video                *VideoDetails `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	SignedUrl            string        `protobuf:"bytes,2,opt,name=signedUrl,proto3" json:"signedUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetVideoResponse) Reset()         { *m = GetVideoResponse{} }
func (m *GetVideoResponse) String() string { return proto.CompactTextString(m) }
func (*GetVideoResponse) ProtoMessage()    {}
func (*GetVideoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{9}
}
func (m *GetVideoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoResponse.Unmarshal(m, b)
}
func (m *GetVideoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoResponse.Marshal(b, m, deterministic)
}
func (dst *GetVideoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoResponse.Merge(dst, src)
}
func (m *GetVideoResponse) XXX_Size() int {
	return xxx_messageInfo_GetVideoResponse.Size(m)
}
func (m *GetVideoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoResponse proto.InternalMessageInfo

func (m *GetVideoResponse) GetVideo() *VideoDetails {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *GetVideoResponse) GetSignedUrl() string {
	if m != nil {
		return m.SignedUrl
	}
	return ""
}

// ----------------------------
// MISC
// ----------------------------
type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_video_61b738b23a955e35, []int{10}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*VideoDetails)(nil), "educonn.video.VideoDetails")
	proto.RegisterType((*VideoStorage)(nil), "educonn.video.VideoStorage")
	proto.RegisterType((*VideoStatus)(nil), "educonn.video.VideoStatus")
	proto.RegisterType((*VideoStatistics)(nil), "educonn.video.VideoStatistics")
	proto.RegisterType((*VideoThumbnail)(nil), "educonn.video.VideoThumbnail")
	proto.RegisterType((*VideoCreatedEvent)(nil), "educonn.video.VideoCreatedEvent")
	proto.RegisterType((*CreateVideoRequest)(nil), "educonn.video.CreateVideoRequest")
	proto.RegisterType((*CreateVideoResponse)(nil), "educonn.video.CreateVideoResponse")
	proto.RegisterType((*GetVideoRequest)(nil), "educonn.video.GetVideoRequest")
	proto.RegisterType((*GetVideoResponse)(nil), "educonn.video.GetVideoResponse")
	proto.RegisterType((*Error)(nil), "educonn.video.Error")
}

func init() { proto.RegisterFile("video.proto", fileDescriptor_video_61b738b23a955e35) }

var fileDescriptor_video_61b738b23a955e35 = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xdb, 0x38,
	0x10, 0x5e, 0xdb, 0xf1, 0xdf, 0x38, 0x7f, 0xcb, 0x0d, 0x16, 0x42, 0x36, 0xdb, 0x3a, 0x44, 0x0f,
	0x3e, 0xb4, 0x36, 0xea, 0x20, 0xc7, 0xf4, 0x90, 0x34, 0x08, 0x82, 0xa6, 0x40, 0xcb, 0xfe, 0x1c,
	0x7a, 0x28, 0xa0, 0x88, 0xac, 0xcc, 0x46, 0x16, 0x1d, 0x92, 0xb2, 0x91, 0x37, 0x2a, 0xd0, 0xd7,
	0xe9, 0x03, 0x15, 0x1c, 0x51, 0xb1, 0xa5, 0x24, 0x3d, 0xe4, 0x24, 0xce, 0x37, 0xdf, 0xcc, 0x7c,
	0x9a, 0x21, 0x07, 0x7a, 0x73, 0xc9, 0x85, 0x1a, 0xce, 0xb4, 0xb2, 0x8a, 0x6c, 0x08, 0x9e, 0x45,
	0x2a, 0x4d, 0x87, 0x08, 0xd2, 0x5f, 0x75, 0x58, 0xff, 0xec, 0x4e, 0xaf, 0x85, 0x0d, 0x65, 0x62,
	0xc8, 0x26, 0xd4, 0x25, 0x0f, 0x6a, 0xfd, 0xda, 0xa0, 0xcb, 0xea, 0x92, 0x93, 0x1d, 0x68, 0x5a,
	0x69, 0x13, 0x11, 0xd4, 0x11, 0xca, 0x0d, 0xd2, 0x87, 0x1e, 0x17, 0x26, 0xd2, 0x72, 0x66, 0xa5,
	0x4a, 0x83, 0x06, 0xfa, 0x56, 0x21, 0x42, 0x60, 0xcd, 0x86, 0xb1, 0x09, 0xd6, 0xfa, 0x8d, 0x41,
	0x97, 0xe1, 0x99, 0x8c, 0xa1, 0x65, 0x6c, 0x68, 0x33, 0x13, 0x34, 0xfb, 0xb5, 0x41, 0x6f, 0xbc,
	0x3b, 0x2c, 0x89, 0x19, 0xa2, 0x90, 0x0f, 0xc8, 0x60, 0x9e, 0x49, 0x5e, 0x01, 0xb8, 0x93, 0x34,
	0x56, 0x46, 0x26, 0x68, 0x61, 0xdc, 0x93, 0x87, 0xe2, 0x72, 0x16, 0x5b, 0x89, 0x20, 0x47, 0x00,
	0x76, 0x92, 0x4d, 0x2f, 0x53, 0xf7, 0x77, 0x41, 0xbb, 0xdf, 0x18, 0xf4, 0xc6, 0xff, 0xdf, 0x17,
	0xff, 0xb1, 0x60, 0xb1, 0x95, 0x00, 0x72, 0x08, 0x6d, 0x63, 0x95, 0x0e, 0x63, 0x11, 0x74, 0xb0,
	0xf6, 0x7f, 0xf7, 0xd7, 0x46, 0x0a, 0x2b, 0xb8, 0xf4, 0xc2, 0x77, 0xd5, 0x3b, 0xc8, 0xbf, 0xd0,
	0xd2, 0xe1, 0xe2, 0x8d, 0xb8, 0xf1, 0x9d, 0xf5, 0x16, 0x79, 0x06, 0x1b, 0x56, 0x87, 0xa9, 0x89,
	0x14, 0x17, 0xdc, 0xb9, 0xf3, 0x2e, 0x97, 0x41, 0xfa, 0xb3, 0x06, 0xbd, 0x95, 0xde, 0x90, 0x3d,
	0xe8, 0x46, 0x6a, 0x3a, 0x4b, 0x84, 0x15, 0xf9, 0xa8, 0x3a, 0x6c, 0x09, 0x90, 0x00, 0xda, 0x8b,
	0x50, 0xa7, 0x32, 0x8d, 0x31, 0x5b, 0x87, 0x15, 0xa6, 0x9b, 0xa5, 0xd0, 0x5a, 0x69, 0x9c, 0x57,
	0x87, 0xe5, 0x06, 0x19, 0xc0, 0x96, 0x27, 0xbc, 0x15, 0xc6, 0x84, 0xb1, 0x28, 0x86, 0x56, 0x85,
	0x9d, 0x5a, 0x0c, 0xb9, 0xe5, 0x35, 0x91, 0x57, 0x06, 0xe9, 0x35, 0x6c, 0x55, 0x06, 0xe2, 0x04,
	0xcf, 0xa5, 0x58, 0x9c, 0xa8, 0x2c, 0xb5, 0x28, 0xb8, 0xc1, 0x96, 0x80, 0xf3, 0x26, 0xf2, 0x4a,
	0xe4, 0xde, 0x7a, 0xee, 0xbd, 0x05, 0x08, 0x85, 0x75, 0x2e, 0x4d, 0x61, 0x73, 0xd4, 0xde, 0x60,
	0x25, 0x8c, 0xbe, 0x83, 0xcd, 0xf2, 0x0c, 0xc9, 0x36, 0x34, 0x32, 0x9d, 0xf8, 0x6e, 0xbb, 0xa3,
	0xfb, 0xf9, 0x85, 0xe4, 0x76, 0x52, 0x5c, 0x64, 0x34, 0xdc, 0x60, 0x26, 0x42, 0xc6, 0x13, 0xeb,
	0xef, 0xb0, 0xb7, 0xe8, 0x57, 0xf8, 0x1b, 0x33, 0x9e, 0x68, 0x11, 0x5a, 0xc1, 0x4f, 0xe7, 0x22,
	0xb5, 0xe4, 0x25, 0x34, 0x71, 0xe8, 0x98, 0xf6, 0x81, 0xab, 0xe0, 0xdf, 0x11, 0xcb, 0x99, 0x2e,
	0x7f, 0x66, 0x84, 0x3e, 0xe7, 0xbe, 0xac, 0xb7, 0xe8, 0x19, 0x90, 0x3c, 0x35, 0x06, 0x31, 0x71,
	0x9d, 0x09, 0xf3, 0x98, 0x02, 0x74, 0x0e, 0xff, 0x94, 0x12, 0x99, 0x99, 0x4a, 0x8d, 0x78, 0x8c,
	0xd4, 0xe7, 0xd0, 0xc2, 0x41, 0x9a, 0xa0, 0x8e, 0xaf, 0x64, 0xa7, 0x12, 0x73, 0xea, 0x9c, 0xcc,
	0x73, 0xe8, 0x3e, 0x6c, 0x9d, 0x09, 0x5b, 0x52, 0x5f, 0x59, 0x1d, 0x34, 0x82, 0xed, 0x25, 0xe5,
	0xf1, 0xba, 0xf6, 0xa0, 0x6b, 0x64, 0x9c, 0x0a, 0xfe, 0x49, 0x27, 0xbe, 0x8b, 0x4b, 0x80, 0x1e,
	0x41, 0x13, 0x85, 0xb9, 0x85, 0xe3, 0x1e, 0x0c, 0x26, 0x6e, 0x32, 0x3c, 0x57, 0xd7, 0x54, 0xfd,
	0xce, 0x9a, 0x1a, 0xff, 0xa8, 0x41, 0x13, 0x8b, 0x92, 0xf7, 0xd0, 0xca, 0x1b, 0x49, 0xf6, 0x2b,
	0xa2, 0xee, 0x0e, 0x6a, 0x97, 0xfe, 0x89, 0x92, 0xff, 0x2a, 0xfd, 0x8b, 0x5c, 0x40, 0xfb, 0x4c,
	0xd8, 0xe3, 0x9b, 0x73, 0x4e, 0xaa, 0x2b, 0xab, 0xd2, 0xbb, 0xdd, 0xa7, 0x0f, 0xfa, 0x8b, 0x6c,
	0xc7, 0x87, 0x5f, 0x0e, 0x62, 0x69, 0x27, 0xd9, 0xe5, 0x30, 0x52, 0xd3, 0x51, 0x92, 0x5d, 0x85,
	0xe6, 0x7b, 0xa8, 0x95, 0x89, 0x26, 0x23, 0x1f, 0xfb, 0x62, 0x96, 0x84, 0xf6, 0x9b, 0xd2, 0xd3,
	0xd1, 0x34, 0x94, 0xc9, 0x08, 0x17, 0xfe, 0x65, 0x0b, 0x3f, 0x07, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x93, 0xcf, 0xf1, 0xec, 0x06, 0x06, 0x00, 0x00,
}
