// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lesson-video/proto/lesson-video.proto

package educonn_lesson_video

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VideoLessonDetails struct {
	VideoId              string   `protobuf:"bytes,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoLessonDetails) Reset()         { *m = VideoLessonDetails{} }
func (m *VideoLessonDetails) String() string { return proto.CompactTextString(m) }
func (*VideoLessonDetails) ProtoMessage()    {}
func (*VideoLessonDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_video_dd0e08d88fa35a74, []int{0}
}
func (m *VideoLessonDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoLessonDetails.Unmarshal(m, b)
}
func (m *VideoLessonDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoLessonDetails.Marshal(b, m, deterministic)
}
func (dst *VideoLessonDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoLessonDetails.Merge(dst, src)
}
func (m *VideoLessonDetails) XXX_Size() int {
	return xxx_messageInfo_VideoLessonDetails.Size(m)
}
func (m *VideoLessonDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoLessonDetails.DiscardUnknown(m)
}

var xxx_messageInfo_VideoLessonDetails proto.InternalMessageInfo

func (m *VideoLessonDetails) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

type CreateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_video_dd0e08d88fa35a74, []int{1}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_lesson_video_dd0e08d88fa35a74, []int{2}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VideoLessonDetails)(nil), "educonn.lesson_video.VideoLessonDetails")
	proto.RegisterType((*CreateRequest)(nil), "educonn.lesson_video.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "educonn.lesson_video.CreateResponse")
}

func init() {
	proto.RegisterFile("lesson-video/proto/lesson-video.proto", fileDescriptor_lesson_video_dd0e08d88fa35a74)
}

var fileDescriptor_lesson_video_dd0e08d88fa35a74 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcd, 0x49, 0x2d, 0x2e,
	0xce, 0xcf, 0xd3, 0x2d, 0xcb, 0x4c, 0x49, 0xcd, 0xd7, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x47,
	0x16, 0xd2, 0x03, 0x0b, 0x09, 0x89, 0xa4, 0xa6, 0x94, 0x26, 0xe7, 0xe7, 0xe5, 0xe9, 0x41, 0xe4,
	0xe2, 0xc1, 0x72, 0x4a, 0x7a, 0x5c, 0x42, 0x61, 0x20, 0x86, 0x0f, 0x58, 0xd0, 0x25, 0xb5, 0x24,
	0x31, 0x33, 0xa7, 0x58, 0x48, 0x82, 0x8b, 0x1d, 0x2c, 0xed, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x19, 0x04, 0xe3, 0x2a, 0xf1, 0x73, 0xf1, 0x3a, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x06, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x09, 0x70, 0xf1, 0xc1, 0x04, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x8d, 0x52, 0xb8, 0xb8, 0x91, 0x8c, 0x14, 0x0a, 0xe5, 0x62, 0x83, 0x28, 0x10, 0x52, 0xd6,
	0xc3, 0xe6, 0x04, 0x3d, 0x14, 0xf3, 0xa4, 0x54, 0xf0, 0x2b, 0x82, 0xd8, 0xa1, 0xc4, 0x90, 0xc4,
	0x06, 0xf6, 0x95, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xdb, 0x76, 0x3c, 0xfe, 0x00, 0x00,
	0x00,
}
